### ISSUE TITLE
Create san-francisco

### ISSUE THREAD

**Issue by suriyaa** [opensourcecities/welcome#10]
ping @RichardLitt and @khos2ow 

----

I created the `san-francisco` repository some weeks ago. Now you can send me any pull requests. 😄 

--[**Suriyaa Sundararuban**](https://suriyaa.tk/) :octocat:

**Comment by RichardLitt** [comment]
I saw that! Thanks! I don't have any PRs to make at the moment; not in the Bay Area anymore (used to be).
