### ISSUE TITLE
Create open-source-munich

### ISSUE THREAD

**Issue by suriyaa** [opensourcecities/welcome#9]
Hello @RichardLitt,

I'm interested to join the @opensourcecities GitHub org. I would like to start the `open-source-munich` project. 🍺 

--[**Suriyaa Sundararuban**](https://suriyaa.tk/) :octocat:

**Comment by RichardLitt** [comment]
Ja! That sounds great. I've created a munich repo (feel free to rename it to München), and added you to the org. 

I would suggest using the [repo_template](https://github.com/opensourcecities/welcome/blob/master/repo_template.md) to get going. Let me know if you need help!

**Comment by suriyaa** [comment]
@RichardLitt I need some admin rights for the `munich` repo. 😅

**Comment by RichardLitt** [comment]
Done!

**Comment by suriyaa** [comment]
@RichardLitt I'm gonna close this issue. 😄
